font_family      JetBrainsMono Nerd Font
font_size        9
letter_spacing   0
disable_ligatures cursor
cursor_shape      beam
cursor_beam_thickness 1.5
background_opacity 0.78
scrollback_lines 10000
window_padding_width 25
placement_strategy center
shell /usr/bin/fish
confirm_os_window_close 0
cursor_trail 1
cursor_trail_decay 0.1 0.4
