[options]
HoldPkg     = pacman glibc
Architecture = auto
IgnorePkg   = 
IgnoreGroup = gnome gnome-extra lxqt lxde cinnamon kde-applications plasma xfce4 xfce4-goodies
NoUpgrade   =
NoExtract = usr/share/man/* usr/share/doc/* usr/share/help/* usr/share/gtk-doc/* usr/share/info/* usr/share/gir-1.0/* usr/share/swcatalog/* usr/share/locale/* !usr/share/locale/pt_BR/* !usr/share/locale/en_US/* usr/include/* usr/lib/python*/test/*
Color
CheckSpace
ParallelDownloads = 10
DownloadUser = alpm
ILoveCandy
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
VerbosePkgLists
DisableDownloadTimeout
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist
